version: '3'
services:
  config:
    image: sms/config-service:1.0
    environment:
      - JAVA_OPTS=
         -DEUREKA_SERVER=http://discovery:8761/eureka         
    depends_on:
      - discovery
    ports:
      - 9000:9000
  discovery:
    image: sms/discovery-service:1.0
    ports:
      - 8761:8761
  gateway:
    image: sms/gateway-service:1.0
    ports:
      - 8085:8085
  authorization-service:
    image: sms/authorization-service:1.0
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://discovery:8761/eureka
    depends_on:
      - discovery
      - config
    ports:
      - 9191:9191
  ui-service:
    image: sms/ui-service:1.0
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://discovery:8761/eureka
    depends_on:
      - discovery
      - config
    ports:
      - 8411:8411
  usermanagement:
    image: sms/usermanagement:1.0
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://discovery:8761/eureka
    depends_on:
      - discovery
      - config
    ports:
      - 9211:9211
  teacher-service:
    image: sms/teacher-service:1.0
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://discovery:8761/eureka
    depends_on:
      - discovery
      - config
    ports:
      - 9200:9200
  student-service:
    image: sms/student-service:1.0
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://discovery:8761/eureka
    restart: on-failure
    depends_on:
      - discovery
      - config
    ports:
      - 9100:9100