version: '3'
services:  
  discovery:
    image: discovery-service:1.0
    ports:
      - 8761:8761
  gateway:
    image: gateway-service:1.0
    ports:
      - 8085:8085
  authorization-service:
    image: authorization-service:1.0
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://discovery:8761/eureka
    depends_on:
      - discovery
      - config
    ports:
      - 9191:9191
  ui-service:
    image: ui-service:1.0
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://discovery:8761/eureka
    depends_on:
      - discovery
      - config
    ports:
      - 8411:8411
  usermanagement:
    image: usermanagement:1.0
    environment:
      - JAVA_OPTS=
        -DEUREKA_SERVER=http://discovery:8761/eureka
    depends_on:
      - discovery
      - config
    ports:
      - 9211:9211